### ISSUE TITLE
Kolize

### ISSUE THREAD

**Issue by vojta001** [Chleboir-CZ/Zelda#1]
Při odrážení ve velmi stísněném prostoru zřídka světelný paprsek proletí skrze stěnu, ale tam následně nekoliduje
![zelda](https://cloud.githubusercontent.com/assets/7038383/9737021/d96b0f2a-5644-11e5-8476-8df691bfc4cc.png)

**Comment by BayerMeister** [comment]
Omyl, je to poslední zrcadlení, koukni, čím smyčka končí. Je to rozhodnutí,
ne bug.

RgB

2015-09-08 16:16 GMT+02:00 vojta001 <notifications@github.com>:
